### PR TITLE
Reintroduction of Mapper

### PR DESCRIPTION
**Pull request by dreymonde**
# Summary

This PR introduces new version of `Mapper`. From now on, `Mapper` is not tied with `Map` (former `StructuredData`), but is **generic, lightweight solution** for mapping any kind of «structured data». So by declaring only one initializer for your model, you can map instance of it from any type which conforms to `MapProtocol` (naming is not final). So, new `Mappable` protocol looks like this:

```swift
public protocol Mappable {   
    init<Map: MapProtocol>(mapper: Mapper<Map>) throws
}
```

Where `MapProtocol` is:

```swift
public protocol MapProtocol {
    subscript(indexPath: IndexPathElement) -> Self? { get }
    subscript(indexPath: [IndexPathElement]) -> Self? { get } // has default implementation
    var asArray: [Self]? { get }
    func get<T>() -> T?
}
```

`Map` and `JSON` conforms to `MapProtocol`.

`Mapper` can:
- Map «nested» mappables.
- Map arrays.
- Map RawRepresentable enum’s *automatically*.

Mapper also supports the concept of «mapping with context». In situation where you want use `Mapper`, but your layout can *differ* between different formats or sources (for example, you may have `createdAt` field name in one place and `created_at` in another), you should use `MappableWithContext` protocol, which conforms to `Mappable`:

```swift
struct User: MappableWithContext {
    
    enum Context {
        case json
        case mongo
    }
    
    let name: String
    let identifier: String
    
    init<Map : MapProtocol>(mapper: ContextualMapper<Map, Context>) throws {
        let context = mapper.context ?? .json
        self.name = try mapper.map(from: "name")
        switch context {
        case .json:
            self.identifier = try mapper.map(from: "id")
        case .mongo:
            self.identifier = try mapper.map(from: "identifier")
        }
    }
    
}

let user = try User(from: userJSON, withContext: .json)
```

And if you want to nest `User` struct inside something else, you can have next type of behavior:

```swift
struct UserBook: MappableWithContext {
    
    let users: [User]
    
    init<Map : MapProtocol>(mapper: ContextualMapper<Map, User.Context>) throws {
        self.users = try mapper.map(arrayWithContextFrom: "users")
    }
    
}
```

Because `User` and `UserBook` share the same associated `Context`, you can just pass context to mapper without any overhead using `.map(withContextFrom:)` and `.map(arrayWithContextFrom:)` methods of `mapper`.

You can also do this:

```swift
struct MongoUserBook: Mappable {
    
    let users: [User]
    
    init<Map : MapProtocol>(mapper: Mapper<Map>) throws {
        self.users = try mapper.map(arrayFrom: "users", usingContext: .mongo)
    }
    
}
```

This PR depends on #34

### CODE REVIEW

**Comment by Danappelxx** [comment]
While we're at it, can we discuss changing the api from `mapper.map(arrayFrom:)` to `mapper.array(at:)`? The `from:` format requires a key, which means that you can't do something like this.

given json
```json
[{
    "id": 10,
    "name": "Dan"
}, {
    "id": 15,
    "name": "Oleg"
}]
```

given model
```swift
struct Person {
    let id: Int
    let name: String
}
struct PersonCollection {
    let people: [Person]
}
```

it is unclear how to write the following code
```swift
// for `PersonCollection`
init<Map: MapProtocol>(mapper: Mapper<Map>) throws {
    self.people = mapper.map(arrayFrom: /* what goes here? */)
}
```

**Comment by dreymonde** [comment]
@Danappelxx interesting problem, thanks. I’ll investigate that.

**Comment by dreymonde** [comment]
@Danappelxx okay, my investigation showed that this test is working nicely (surprisingly):

```swift
func testFlatArray() {

    struct Person: Mappable {
        let id: Int
        let name: String
        
        init<Map : MapProtocol>(mapper: Mapper<Map>) throws {
            self.id = try mapper.map(from: "id")
            self.name = try mapper.map(from: "name")
        }
    }
    
    struct PersonCollection: Mappable {
        let people: [Person]
        
        init<Map : MapProtocol>(mapper: Mapper<Map>) throws {
            self.people = try mapper.map()
        }
    }
    
    let dict: Map = [["id": 15, "name": "Alfred"], ["id": 21, "name": "Bruce"]]
    let collection = try! PersonCollection(from: dict)
    print(collection)
// (PersonCollection #1)(people: [QuarkTests.MapperTests.(testFlatArray () -> ()).(Person #1)(id: 15, name: "Alfred"), QuarkTests.MapperTests.(testFlatArray () -> ()).(Person #1)(id: 21, name: "Bruce")])
}
```

I can’t fully understand how Swift choose to use `map(arrayFrom:)` version here, but anyway it did the right choice.

**Comment by dreymonde** [comment]
Waiting for #34 to merge.

**Pull request closed without merging**
