### PR TITLE
Generic InMapper & OutMapper

### PR DESCRIPTION
**Pull request by dreymonde**
Please, review the naming, protocol requirements and so on, so I can move to writing tests.

Example:

``` swift
// Mappable = InMappable & OutMappable
struct Human: Mappable {
    let name: String
    let age: Int
    let nicknames: [String]

    enum Keys: String, IndexPathElement {
        case name
        case age
        case nicknames
    }

    init<Map : InMapProtocol>(mapper: InMapper<Map, Keys>) throws {
        self.name = try mapper.map(from: .name)
        self.age = try mapper.map(from: .age)
        self.nicknames = try mapper.map(arrayFrom: .nicknames)
    }

    func outMap<Map : OutMapProtocol>(mapper: inout OutMapper<Map, Keys>) throws {
        try mapper.map(self.name, to: .name)
        try mapper.map(self.age, to: .age)
        try mapper.map(array: self.nicknames, to: .nicknames)
    }
}

let map: Map = ["name": "Bruce Wayne", "age": 31, "nicknames": ["Batman", "The Dark Knight"]]
let batman = try Human(from: map)
// (name: "Bruce Wayne", age: 31, nicknames: ["Batman", "The Dark Knight"])
let batmanMap: Map = try batman.map()
// {"age":31,"name":"Bruce Wayne","nicknames":["Batman","The Dark Knight"]}
```

### CODE REVIEW

**Comment by Danappelxx** [comment]
I'm still not a huge fan of the `from` methods, which use labels to distinguish between themselves. What about `map.value`, `map.array`, etc.?

Other than that, looks great!

**Comment by dreymonde** [comment]
Can you please suggest the exact naming? Using the example in the PR description.

**Comment by paulofaria** [comment]
I'm thinking maybe the naming could be better as `InputMapper` and `OutputMapper`? I'm not sure the `In` and `Out` are good enough.

**Comment by dreymonde** [comment]
@paulofaria not sure… The problem is that it’s not actually «Input»/«Output». Using this terms here can be confusing.

**Pull request closed without merging**
